server:
  port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kboom/orb-static-server-config.git
          username: ${GITHUB_LOGIN}
          password: ${GITHUB_PASS}