server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://kbhit@bitbucket.org/kbhit/orangebox-server-config.git
          username: kbhit
          password: zLg9D2gg